name: view_selector_example2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  intl: ^0.20.2  
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  open_file: ^3.5.10
  path_provider: ^2.0.10
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  shared_preferences: ^2.3.3
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.16
  simple_animations: ^5.1.0
  local_auth: ^2.3.0
  connectivity_plus: ^6.1.1
  # PDF packages with built-in Google Fonts support
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/asicon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf

  assets:
    - assets/logo.png
    - assets/fonts/
    - assets/header.svg  # Add this line for your SVG header